services:
  - type: web
    name: localgigs
    runtime: ruby
    plan: free
    buildCommand: "bundle install && bin/rails tailwindcss:build && bin/rails assets:precompile && bin/rails db:migrate"
    startCommand: "bin/rails server -b 0.0.0.0"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: localgigs-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
databases:
  - name: localgigs-db
    plan: free
